config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
  end

end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :gist_url, presence: true
end

app/controllers/admin/gists_controller.rb
class Admin::GistsController < Admin::BaseController

  def index
    @gists = Gist.all
  end

end

app/views/admin/gists/_gist.html.erb
<tr>
  <td><%= link_to truncate(gist.question.body, length: 25), admin_question_path(gist.question)%></td>
  <td><%= link_to gist.gist_url, gist.gist_url %></td>
  <td><%= gist.user.email %></td>
</tr>

app/views/admin/gists/index.html.erb
<div class="row justify-content-center mt-5">
  <div class="col col-md-6">
    <h2 class="text-center"> Gists list</h2>
      <%= link_to 'Back', admin_tests_path %>
    <table class="table text-center">
      <thead class="thead" style="background-color: lightgray";>
        <tr>
          <th><%= t('.question')%></th>
          <th><%= t('.gist_link')%></th>
          <th><%= t('.user_email') %></th>
        </tr>
      </thead>
     <%= render @gists %>
    </table>
  </div>
</div>