config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :validation_next_question, on: %i[create update]

  SCORE_POINTS = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
    save!
  end

  def score_percentage
    (correct_questions.to_f / count_test_questions * 100).round
  end

  def test_passed?
    score_percentage >= SCORE_POINTS
  end

  def number_current_question
    count_test_questions - last_questions.count
  end

  def count_test_questions
    test.questions.count
  end

  private

  def validation_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def last_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def next_question
    if current_question.nil? && test.present?
      test.questions.first
    else
      last_questions.first
    end
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show
  end

  def result
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call
    if result.html_url.present?
      current_user.gists.create(question: @test_passage.current_question, gist_url: result.html_url)
      flash[:notice] = t('.success', gist_url: result.html_url)
      redirect_to @test_passage
    else
      flash[:alert] = t('.failure')
      redirect_to @test_passage
    end
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h2><%= t('.header', title: @test_passage.test.title) %><h2>

<p>
  <% if @test_passage.test_passed? %>
    <%= t('.score') %>
    <span class="positive"><%= @test_passage.score_percentage%>%!</span>
    <%= t('.positive_msg') %>
  <% else %>
    <%= t('.score') %>
    <span class="negative"><%= @test_passage.score_percentage%>%!</span>!
    <%= t('.negative_msg') %>
  <% end %>
</p>

<p><%= link_to t('.tests_list'), tests_path %></p>

app/views/test_passages/show.html.erb
<h2>
  <%= t('.header', title: @test_passage.test.title).html_safe %>
</h2>

<p>
  <%= t('.question', question: @test_passage.number_current_question) %> / <%= @test_passage.count_test_questions %>
</p>
<%= content_tag :div, class: 'progress', data: {
    current: @test_passage.number_current_question,
    total:  @test_passage.count_test_questions} do %>
  <div class="progress-bar bg-success" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
    0%
  </div>
<% end  %>
<p>
  <b><%= @test_passage.current_question.body%></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('.next') %></p>
<% end %>