config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show edit update destroy]

  #rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found


  def show
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@test)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test_id)
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: "Заданный вопрос не найден!"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Редактировать вопрос: '#{question.body}'"
    else
      "Создание нового вопроса для теста: '#{question.test.title}'"
    end
  end
end

app/views/admin/questions/_form.html.erb
<h2><%= question_header(@question) %></h2>

<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :Вопрос %><br>
    <%= form.text_field :body, id: :question_body%>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('.show_question'), admin_question_path(question) %></td>
  <td><%= link_to t('.edit_question'), edit_admin_question_path(question) %></td>
  <td>
    <%= link_to t('.delete_question'),
                  admin_question_path(question),
                  method: :delete,
                  data: {confirm: 'Вы уверены?' } %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>
<p></p>
<%= link_to 'Назад', admin_test_path(@question.test_id) %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>
<p></p>
<%= link_to 'Назад', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h2>Тест: &#171;<%= @question.test.title %>&#187;</h2>

<p>
  Вопрос: <%= @question.body %>
</p>

<h3>Ответы:</h3>

<%= link_to "Новый ответ", new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers%>
</ol>

<%= link_to 'Назад', admin_test_path(@question.test_id) %>